# Generated by Django 5.1.6 on 2025-02-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_hotel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="spots",
        ),
    ]
